language: python
python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
    - pip install coveralls

script:
    - ./run-tests.sh -n

after_success:
    coveralls
